# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c418d76d9b04a7ef2662e2e3419fd819a4250ed68280538727a65f5fb33efec87c9f2dbb202b1ffd439638410474bbd153a3f3e6b86ffbb81c9cee99e9339363

test:
  secret_key_base: 7319f6f8c2ffdd4b643131b76bf07b0c747e4b419edfbe019510e3e1c7b3968570ff8e85a8918f1590a8b4d8dc402cde4e24e7e8c6882ae16ca4ef595da4b358

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
