# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
if Exercise.count == 0
  Exercise.create!( name: "Crunches"    , exercise_index: 20)
  Exercise.create!( name: "Walking"	    , exercise_index: 15)
  Exercise.create!( name: "Running"	    , exercise_index: 40)
  Exercise.create!( name: "Sprinting"	  , exercise_index: 60)
  Exercise.create!( name: "Squats"	    , exercise_index: 60)
  Exercise.create!( name: "Bench press"	, exercise_index: 45)
end


if Food.count == 0
  Food.create!( name: "Banana cake, made with sugar" , glycemic_index: 47)
  Food.create!( name: "Banana cake, made without sugar" , glycemic_index: 55)
  Food.create!( name: "Sponge cake, plain" , glycemic_index: 46)
  Food.create!( name: "Vanilla cake made from packet mix with vanilla frosting (Betty Crocker)" , glycemic_index: 42)
  Food.create!( name: "Apple, made with sugar" , glycemic_index: 44)
  Food.create!( name: "Apple, made without sugar" , glycemic_index: 48)
  Food.create!( name: "Waffles, Aunt Jemima (Quaker Oats)" , glycemic_index: 76)
  Food.create!( name: "Bagel, white, frozen" , glycemic_index: 72)
  Food.create!( name: "Baguette, white, plain" , glycemic_index: 95)
  Food.create!( name: "Coarse barley bread, 75-80% kernels, average" , glycemic_index: 34)
  Food.create!( name: "Hamburger bun" , glycemic_index: 61)
  Food.create!( name: "Kaiser roll" , glycemic_index: 73)
  Food.create!( name: "Pumpernickel bread" , glycemic_index: 56)
  Food.create!( name: "50% cracked wheat kernel bread" , glycemic_index: 58)
  Food.create!( name: "White wheat flour bread" , glycemic_index: 71)
  Food.create!( name: "Wonder™ bread, average" , glycemic_index: 73)
  Food.create!( name: "Whole wheat bread, average" , glycemic_index: 71)
  Food.create!( name: "100% Whole Grain™ bread (Natural Ovens)" , glycemic_index: 51)
  Food.create!( name: "Pita bread, white" , glycemic_index: 68)
  Food.create!( name: "Corn tortilla" , glycemic_index: 52)
  Food.create!( name: "Wheat tortilla" , glycemic_index: 30)
  Food.create!( name: "Coca Cola®, average" , glycemic_index: 63)
  Food.create!( name: "Fanta®, orange soft drink" , glycemic_index: 68)
  Food.create!( name: "Lucozade®, original (sparkling glucose drink)" , glycemic_index: 95)
  Food.create!( name: "Apple juice, unsweetened, average" , glycemic_index: 44)
  Food.create!( name: "Cranberry juice cocktail (Ocean Spray®)" , glycemic_index: 68)
  Food.create!( name: "Gatorade" , glycemic_index: 78)
  Food.create!( name: "Orange juice, unsweetened" , glycemic_index: 50)
  Food.create!( name: "Tomato juice, canned" , glycemic_index: 38)
  Food.create!( name: "All-Bran™, average" , glycemic_index: 55)
  Food.create!( name: "Coco Pops™, average" , glycemic_index: 77)
  Food.create!( name: "Cornflakes™, average" , glycemic_index: 93)
  Food.create!( name: "Cream of Wheat™ (Nabisco)" , glycemic_index: 66)
  Food.create!( name: "Cream of Wheat™, Instant (Nabisco)" , glycemic_index: 74)
  Food.create!( name: "Grapenuts™, average" , glycemic_index: 75)
  Food.create!( name: "Muesli, average" , glycemic_index: 66)
  Food.create!( name: "Oatmeal, average" , glycemic_index: 55)
  Food.create!( name: "Instant oatmeal, average" , glycemic_index: 83)
  Food.create!( name: "Puffed wheat, average" , glycemic_index: 80)
  Food.create!( name: "Raisin Bran™ (Kellogg's)" , glycemic_index: 61)
  Food.create!( name: "Special K™ (Kellogg's)" , glycemic_index: 69)
  Food.create!( name: "Pearled barley, average" , glycemic_index: 28)
  Food.create!( name: "Sweet corn on the cob, average" , glycemic_index: 60)
  Food.create!( name: "Couscous, average" , glycemic_index: 65)
  Food.create!( name: "Quinoa" , glycemic_index: 53)
  Food.create!( name: "White rice, average" , glycemic_index: 89)
  Food.create!( name: "Quick cooking white basmati" , glycemic_index: 67)
  Food.create!( name: "Brown rice, average" , glycemic_index: 50)
  Food.create!( name: "Converted, white rice (Uncle Ben's®)" , glycemic_index: 38)
  Food.create!( name: "Whole wheat kernels, average" , glycemic_index: 30)
  Food.create!( name: "Bulgur, average" , glycemic_index: 48)
  Food.create!( name: "Graham crackers" , glycemic_index: 74)
  Food.create!( name: "Vanilla wafers", glycemic_index: 77)
  Food.create!( name: "Shortbread" , glycemic_index: 64)
  Food.create!( name: "Rice cakes, average" , glycemic_index: 82)
  Food.create!( name: "Rye crisps, average" , glycemic_index: 64)
  Food.create!( name: "Soda crackers" , glycemic_index: 74)
  Food.create!( name: "Ice cream, regular" , glycemic_index: 57)
  Food.create!( name: "Ice cream, premium" , glycemic_index: 38)
  Food.create!( name: "Milk, full fat" , glycemic_index: 41)
  Food.create!( name: "Milk, skim" , glycemic_index: 32)
  Food.create!( name: "Reduced-fat yogurt with fruit, average" , glycemic_index: 33)
  Food.create!( name: "Apple, average" , glycemic_index: 39)
  Food.create!( name: "Banana, ripe" , glycemic_index: 62)
  Food.create!( name: "Dates, dried" , glycemic_index: 42)
  Food.create!( name: "Grapefruit" , glycemic_index: 25)
  Food.create!( name: "Grapes, average" , glycemic_index: 59)
  Food.create!( name: "Orange, average" , glycemic_index: 40)
  Food.create!( name: "Peach, average" , glycemic_index: 42)
  Food.create!( name: "Peach, canned in light syrup" , glycemic_index: 40)
  Food.create!( name: "Pear, average" , glycemic_index: 38)
  Food.create!( name: "Pear, canned in pear juice" , glycemic_index: 43)
  Food.create!( name: "Prunes, pitted" , glycemic_index: 29)
  Food.create!( name: "Raisins" , glycemic_index: 64)
  Food.create!( name: "Watermelon" , glycemic_index: 72)
  Food.create!( name: "Baked beans, average" , glycemic_index: 40)
  Food.create!( name: "Blackeye peas, average" , glycemic_index: 33)
  Food.create!( name: "Black beans" , glycemic_index: 30)
  Food.create!( name: "Chickpeas, average" , glycemic_index: 10)
  Food.create!( name: "Chickpeas, canned in brine" , glycemic_index: 38)
  Food.create!( name: "Navy beans, average" , glycemic_index: 31)
  Food.create!( name: "Kidney beans, average" , glycemic_index: 29)
  Food.create!( name: "Lentils, average" , glycemic_index: 29)
  Food.create!( name: "Soy beans, average" , glycemic_index: 15)
  Food.create!( name: "Cashews, salted" , glycemic_index: 27)
  Food.create!( name: "Peanuts, average" , glycemic_index: 7)
  Food.create!( name: "Fettucini, average" , glycemic_index: 32)
  Food.create!( name: "Macaroni, average" , glycemic_index: 47)
  Food.create!( name: "Macaroni and Cheese (Kraft)" , glycemic_index: 64)
  Food.create!( name: "Spaghetti, white, boiled, average" , glycemic_index: 46)
  Food.create!( name: "Spaghetti, white, boiled 20 min, average" , glycemic_index: 58)
  Food.create!( name: "Spaghetti, wholemeal, boiled, average" , glycemic_index: 42)
  Food.create!( name: "Corn chips, plain, salted, average" , glycemic_index: 42)
  Food.create!( name: "Fruit Roll-Ups®" , glycemic_index: 99)
  Food.create!( name: "M & M's®, peanut" , glycemic_index: 33)
  Food.create!( name: "Microwave popcorn, plain, average" , glycemic_index: 55)
  Food.create!( name: "Potato chips, average" , glycemic_index: 51)
  Food.create!( name: "Pretzels, oven-baked" , glycemic_index: 83)
  Food.create!( name: "Snickers Bar®" , glycemic_index: 51)
  Food.create!( name: "Carrots, average" , glycemic_index: 35)
  Food.create!( name: "Parsnips" , glycemic_index: 52)
  Food.create!( name: "Baked russet potato, average" , glycemic_index: 111)
  Food.create!( name: "Boiled white potato, average" , glycemic_index: 82)
  Food.create!( name: "Instant mashed potato, average" , glycemic_index: 87)
  Food.create!( name: "Sweet potato, average" , glycemic_index: 70)
  Food.create!( name: "Yam, average" , glycemic_index: 54)
  Food.create!( name: "Green peas, average" , glycemic_index: 51)
  Food.create!( name: "Hummus (chickpea salad dip)" , glycemic_index: 6)
  Food.create!( name: "Chicken nuggets, frozen, reheated in microwave oven 5 min" , glycemic_index: 46)
  Food.create!( name: "Pizza, plain baked dough, served with parmesan cheese and tomato sauce" , glycemic_index: 80)
  Food.create!( name: "Pizza, Super Supreme (Pizza Hut)" , glycemic_index: 36)
  Food.create!( name: "Honey, average" , glycemic_index: 61)
end
